---
# defaults file for web_server

web_server_package: httpd
web_server_service: httpd
web_server_state: present
web_server_path: /var/www/html/
web_server_index: index.html
web_server_content: "Simple Level 2 Defaults"
